function [ch_roi_name,c_roi_name,s_roi_name]=gen_roi_name()
%function [h_roi_name]=gen_roi_name()
%%%%%%%%%
basedir='/seastor/helenhelen/Cicero';
behavdir='/seastor/Projects/Cicero/exp-scripts/Mol/Results_scan';
datadir=sprintf('%s/pattern/ROI_based/ref_space/raw',basedir);
zdir=sprintf('%s/pattern/ROI_based/ref_space/z',basedir);
addpath /seastor/helenhelen/scripts/NIFTI
%%%%%%%%%
ch_roi_name={...
'LCC','LVVC','LvLOC','LdLOC',...
'LITG','LMTG',...
'LpFUS','LOF','LTOF','LpTF','LaTF',...
'LIPL','LSPL','LANG','LSMG','LpSMG','LaSMG',...
'LHIP','LPHG','LpPHG','LaPHG',...
'LIFG','LMFG','LSFG',...
'RCC','RVVC','RvLOC','RdLOC',...
'RITG','RMTG',...
'RpFUS','ROF','RTOF','RpTF','RaTF',...
'RIPL','RSPL','RANG','RSMG','RpSMG','RaSMG',...
'RHIP','RPHG','RpPHG','RaPHG',...
'RIFG','RMFG','RSFG',...
'mPFC','PCC',...
'CA1','CA2','DG','CA3','subiculum','PRC','ERC',...
'left_CA1','left_CA2','left_DG','left_CA3','left_subiculum','left_PRC','left_ERC',...
'right_CA1','right_CA2','right_DG','right_CA3','right_subiculum','right_PRC','right_ERC',...
'hCA1','hDG','hsubiculum',...
'bCA1','bDG','bsubiculum',...
'tCA1','tDG','tsubiculum',...
'left_hCA1','left_hDG','left_hsubiculum',...
'left_bCA1','left_bDG','left_bsubiculum',...
'left_tCA1','left_tDG','left_tsubiculum',...
'right_hCA1','right_hDG','right_hsubiculum',...
'right_bCA1','right_bDG','right_bsubiculum',...
'right_tCA1','right_tDG','right_tsubiculum'};

c_roi_name={...
'LCC','LVVC','LvLOC','LdLOC',...
'LITG','LMTG',...
'LpFUS','LOF','LTOF','LpTF','LaTF',...
'LIPL','LSPL','LANG','LSMG','LpSMG','LaSMG',...
'LHIP','LPHG','LpPHG','LaPHG',...
'LIFG','LMFG','LSFG',...
'RCC','RVVC','RvLOC','RdLOC',...
'RITG','RMTG',...
'RpFUS','ROF','RTOF','RpTF','RaTF',...
'RIPL','RSPL','RANG','RSMG','RpSMG','RaSMG',...
'RHIP','RPHG','RpPHG','RaPHG',...
'RIFG','RMFG','RSFG',...
'mPFC','PCC'};

h_roi_name={
'CA1','CA2','DG','CA3','subiculum','PRC','ERC'};

sh_roi_name={
'left_CA1','left_CA2','left_DG','left_CA3','left_subiculum','left_PRC','left_ERC',...
'right_CA1','right_CA2','right_DG','right_CA3','right_subiculum','right_PRC','right_ERC'};

s_roi_name={...
    'LVVC',...
    'LANG','LSMG',...
    'LpPHG',...
    'LIFG',...
    'RVVC',...
    'RANG','RSMG',...
    'RpPHG',...
    'mPFC','PCC',...
    'hCA1','hDG','hsubiculum',...
    'bCA1','bDG','bsubiculum',...
    'tCA1','tDG','tsubiculum'};

%'left_CA1','left_DG','left_subiculum','left_PRC','left_ERC'...
%'right_CA1','right_DG','right_subiculum','right_PRC','right_ERC'};

a_roi_name={...
    'hCA1','hDG','hsubiculum',...
    'bCA1','bDG','bsubiculum',...
    'tCA1','tDG','tsubiculum',...
    'left_hCA1','left_hDG','left_hsubiculum',...
    'left_bCA1','left_bDG','left_bsubiculum',...
    'left_tCA1','left_tDG','left_tsubiculum',...
    'right_hCA1','right_hDG','right_hsubiculum',...
    'right_bCA1','right_bDG','right_bsubiculum',...
    'right_tCA1','right_tDG','right_tsubiculum'};
